version: '3'

services:

  # postgresql container
  db_postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - todo_app_network

  # pgadmin container
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db_postgres
    networks:
      - todo_app_network

volumes:
  postgresdata:

networks:
  todo_app_network:
    driver: bridge
